### ISSUE TITLE
Wayland

### ISSUE THREAD

**Issue by kaberc** [mjkillough/cnx#30]
Any wayland support soon?

**Comment by mjkillough** [comment]
I don't use Wayland, so it's unlikely to be something I work on in the medium term.

I know there is some X11/Wayland compatiblity shims... it might be possible to have the bar render using XCB, but running on top of Wayland? I imagine Wayland is not going to be using EHWM, so you'd probably need to create your own widgets to interface with your window manager. I am not sure if there's an equivalent to the EHWM standard on Wayland.

**Comment by mjkillough** [comment]
I hope you don't mind, but I'm going to close this as I don't plan on supporting Wayland in the future.
