### ISSUE TITLE
Make master compatible with Linux

### ISSUE THREAD

**Issue by psibi** [mjkillough/cnx#33]
I see that a related issue was open already but it has been closed: https://github.com/mjkillough/cnx/issues/32

I'm planning to try out cnx and possibly make it as my status bar. But unfortunately it seem the master doesn't seem to be working with Linux.

From looking further it seems to be because of `sioctl` which is introduced in the volume widget. Would you be willing it to make it behind an optional feature instead: https://doc.rust-lang.org/cargo/reference/features.html

I can also volunteer to send a PR for the same. :-)

**Comment by psibi** [comment]
I have created a PR which makes it compile under Linux system: https://github.com/mjkillough/cnx/pull/34

I also noted that the volume and the sensors plugin in master doesn't seem to be working under Linux system. Looking at the code, it seems to be tailored for BSD operating systems. I would be interested to add add support for Linux too. Is the upstream interested in such changes ?

**Comment by mjkillough** [comment]
> I also noted that the volume and the sensors plugin in master doesn't seem to be working under Linux system. Looking at the code, it seems to be tailored for BSD operating systems. I would be interested to add add support for Linux too. Is the upstream interested in such changes ?

If this would be useful for you, you'd be very welcome to make the change! 

There are a couple of places in the code where I have placed `type Widget = OpenBsd;` (e.g. in [`volume.rs`](https://github.com/mjkillough/cnx/blob/master/src/widgets/volume.rs#L78) and I think in the battery/sensors widgets too). I'd imagined that there would be both `OpenBsd` and `Linux` types which implement the same methods but generate informatation using platform specific methods. The `OpenBsd` type would be `#[cfg(target_os ="openbsd")]` and the `Linux` type would be `#[cfg(target_os = "linux")]`.

**Comment by psibi** [comment]
Thanks for the reply! I would be slowly sending PR's as I make things work on my machine (and as I find time!). Thanks for creating cnx. :-)

**Comment by psibi** [comment]
Closing this as master is compatible with Linux now.
