### ISSUE TITLE
active_window_title widget doesn't change when switching to an empty tag.

### ISSUE THREAD

**Issue by mejo13** [mjkillough/cnx#36]
So the window title just stays the same instead of going blank. Is this the expected behavior or is my setup bugged?
Greetings mejo

**Comment by psibi** [comment]
@mejo13 Is this still reproducible in the latest master branch ? I tested this in my setup and for me it goes blank if I go to a workspace where there is no windows.

**Comment by psibi** [comment]
I'm closing this issue as there is not enough information to debug further.
