### ISSUE TITLE
Volume Widget doesn't update

### ISSUE THREAD

**Issue by 72siddharth** [mjkillough/cnx#44]
The value displayed by the volume widget doesn't update but remains as the same value when starting the bar.
That is if the volume is 70% when starting the bar, the value displayed by the widget remains 70% even if I increase or decrease the volume.
Os - Garuda Linux Soaring

**Comment by psibi** [comment]
I was able to reproduce this issue under NixOS (It seemed to work fine under my Ubuntu machine) and I think I know why this is happening: The events at the alsa aren't being handled. I'm planning to have the fix ready by next week.

Thanks for the bug report!

**Comment by psibi** [comment]
@72siddharth Can you see if this PR fixes it for you: https://github.com/mjkillough/cnx/pull/45 ?
