### ISSUE TITLE
 Rust toolchain

### ISSUE THREAD

**Issue by VuiMuich** [mjkillough/cnx#50]
Is there a specific reason, why the rust toolchain is fixed to `1.50.0`?
It compiles well with 1.56.1

**Comment by psibi** [comment]
No specific reasons, I would be happy to accept a PR accepting a bump.

**Comment by VuiMuich** [comment]
Why not simply remove the override and use whatever the default toolchain cargo is using?

**Comment by psibi** [comment]
This is mostly to ensure reproducibility for ease of development. Having a combination of toolchain file and [shell.nix](https://github.com/mjkillough/cnx/blob/master/shell.nix) ensures to me the last known version of compiler that I knew it worked with.

Also, the CI jobs are run against that compiler. That being said, I belive for the consumers of the above two crates (cnx and cnx-contrib), it doesn't matter as they aren't tied to a single rust version

**Comment by VuiMuich** [comment]
I see..
