### ISSUE TITLE
Allow to specify the width and offset of the bar

### ISSUE THREAD

**Issue by Sh4d1** [mjkillough/cnx#58]
Hey ! Nice project, just getting started with it!

I have this use case, with 2 monitors, where I want a bar on each monitor.

Currently, it just stretches across the 2 monitors. 
I have a small patch that add 2 `Option`s to the `Bar::new` , namely `width` and `x_offset`. 
I feel it's just a quickhack :sweat_smile: 

`height` is not useful AFAIK, and `y_offset` makes not much sense (well it could maybe, not sure). 

I was thinking of maybe adding some `with_x_offset`, `with_width` to the `Bar` struct, wdyt?

**Comment by psibi** [comment]
Sure, I don't see any problem. As long as it doesn't break the single monitor use case by default and it has good documentation, it should be good to go. Free feel to send a PR.
